# URL of RSS feed that lists all available ZIM archives (paginated).
# https://kiwix-tools.readthedocs.io/en/latest/kiwix-serve.html#catalog-v2-entries
rss_base_url = "https://browse.library.kiwix.org/catalog/v2/entries"

# Base directory where ZIM archives, library file and database file will be stored.
base_dir = "/path/to/base/dir"

# Whether to delete older versions of the same archive when a new version is found.
delete_old = true

# Path to the `kiwix-manage` tool, used to manage the library file.
kiwix_manage_exec = "/usr/bin/kiwix-manage"

# For each archive, specify the name, flavor and language, in each case as specified in the RSS feed.
# Language and name are required. If not supplied, flavor will default to None. All elements (name, flavor and language)
# must match exactly with what is present in the RSS feed.

[[archive]]
name = "archlinux_en_all"
flavor = "maxi"
language = "eng"

[[archive]]
name = "history.stackexchange.com_en_all"
flavor = "all"
language = "eng"

[[archive]]
name = "law.stackexchange.com_en_all"
flavor = "all"
language = "eng"